# Event - What starts this workflow?
on:
  workflow_dispatch:

# Name of the workflow
name: hello-r-world

run-name: ${{ github.actor }} is learning Github Actions

# Jobs - What the computer should do? 
jobs:
  write-message:
    # Use Ubuntu   
    runs-on: ubuntu-latest 
    steps:
       # Install R
      - uses: r-lib/actions/setup-r@v3    
      - name: print-message   
        # Code to execute R script
        run: Rscript -e 'print("Hello R World!")' 