
name: first_action

# Controls when the action will run.
on:
  
  # # Scheduled 
  # schedule:
  #   - cron:  '0 13 * * *'
  
  # # Triggered on push and pull request events
  # push:
  # pull_request:
  
  # Allow manual runs from the Actions tab
  workflow_dispatch:


jobs: 
  basic:
    # The type of runner that the job will run on
    # (below syntax from https://mirai-solutions.ch/techguides/github-actions.html)
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    
    strategy:
      # We keep a matrix for convenience, but we would typically just run on one
      # single OS and R version, aligned with the target deployment environment
      
      matrix:
        config:
         - {os: ubuntu-latest, r: 'release'}
         
    env:
     # Access token for Github
     GITHUB_PAT: ${{ secrets.GH_TOKEN }}
     
     # Preserve package sources for informative references in case of errors
     R_KEEP_PKG_SOURCE: yes

    # Load repo and install R
    steps:
    
    - name: Checkout master
      uses: actions/checkout@master
    
    - name: Install libcurl
      run: sudo apt-get install libcurl4-openssl-dev
      
    - name: Setup R
      uses: r-lib/actions/setup-r@master
    
    - name: Setup renv        
      uses: r-lib/actions/setup-renv@v2
    
    - name: Run renv::restore()
      run: Rscript -e "renv::restore()"

    - name: Run print_datetime.R
      run: Rscript print_datetime.R
      
