# Event - What starts this workflow?
on:
  workflow_dispatch:

# Name of the workflow
name: test_02

run-name: ${{ github.actor }} is running test_02

# Jobs - What the computer should do? 
jobs:
  print-hello:
    
    # Use Ubuntu   
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v3
      
      # Install R (without specifying a version)
      - uses: r-lib/actions/setup-r@v2
      
      - name: print-message   
        # Code to execute R script
        run: Rscript -e 'print("hello from test_02")' 