# Event - What starts this workflow?
on:
  workflow_dispatch:

# Name of the workflow
name: test_04

run-name: ${{ github.actor }} is running test_04

# Jobs - What the computer should do? 
jobs:
  test4:
    
    # Use Ubuntu   
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      
      - name: print-message   
        # Code to execute R script
        run: Rscript -e 'print("hello from test_04")'
        
      - name: print-timeanddate
        run: Rscript -e "print(paste0('Today is: ', Sys.Date()))"
        
      # - name: print-date
      #   run: Rscript -e 'cli::cli_inform("{lubridate::now(tzone = 'UTC')}")'